### PR TITLE
Feature to return the current TaskId into the Tasks handler

### LINKED ISSUE #179: How can I retrieve the TaskId or JobId in the handler?
I'd like to know what task or job is being executed in the handler.  Is that possible?

### PR DESCRIPTION
**Pull request by Extend-Apps**
Closes #179

### CODE REVIEW

**Review by kibertoad — CHANGES_REQUESTED** [review]
Documentation is necessary.

Can you also please explain what is your use-case for this?

**Comment by Extend-Apps** [comment]
@kibertoad , I reverted the namespace change (apologies for that) and updated issue #179 .  The PR includes supporting tests as well.  Hoping you merge this as I'm surprised it's not been asked for in the past.

**Review by kibertoad — APPROVED** [review]

**Comment by Extend-Apps** [comment]
maybe tonight?

**Comment by kibertoad** [comment]
let me do few more changes, and then I'll publish it, sorry for the delay

**Comment by Extend-Apps** [comment]
No sorry needed my friend.  Thanks again

**Pull request merged**
