### PR TITLE
Implement support for long intervals

### LINKED ISSUE #24: Scheduling breaks completely on long intervals
I stumbled upon toad-scheduler while looking for an improved alternative to the native setInterval and I'm liking the simplicity of this project, great job on that aspect.

However this library doesn't fix a crucial core problem of vanilla Timers: The timeout length must fit into a signed 32-bit integer.
It's a quite frankly pretty unnecessary limit of NodeJS and most browsers, you can not set a timeout for longer than 

> 2 ^ 31 - 1 = 2 147 483 647

 milliseconds. Now that seems like a lot but take this example:

```
const { ToadScheduler, SimpleIntervalJob, Task } = require('toad-scheduler')

const scheduler = new ToadScheduler()

let myTask = new Task('someString', () => { console.log("I've waited a long time for this") })
let myJob = new SimpleIntervalJob({ hours: 720, }, myTask) // or { days: 30, }

scheduler.addSimpleIntervalJob(myJob)
```

The goal of this code would be executing the Task every 30 days, which is a reasonable interval time for server sided applications in my opinion. However this will instantly break with this warning:

> (node:4229) TimeoutOverflowWarning: 2592000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.

That's because neither setTimeout or setInterval can handle anything bigger than 24.85 days of a timeout. Now since this module also uses these functions without modification, the same limits apply and the timeout gets set to 1ms right after the warning, meaning your console will be spammed into oblivion when running this.

Now I realize this scheduler is more focused on shorter, more repetitive tasks but I still think this is a fix-worthy issue. Especially because this shouldn't be extremely hard to fix once you understand where this limit applies.

### PR DESCRIPTION
**Pull request by AndreWillomitzer**
fixes #24

### CODE REVIEW

**Comment by AndreWillomitzer** [comment]
@kibertoad 
Hope all is well I bet you're busy and I feel bad messaging ya but with my professors help we managed to modify the constructor code, and now when I run the test for long intervals it says 1 of 1 passed. If I run all the tests it says 3 of 6 passed 3 failed. Would you be able to help me inspect why it fails the other tests? 
image

It passes the test and then kind of just hangs there in the terminal like it's waiting for the task, even though I used advanceTimersByTime().

All the best,

Andre

**Comment by kibertoad** [comment]
Hey, Andre! 
Sorry for the delay in replying. Will take a look on it tonight!

**Comment by AndreWillomitzer** [comment]
@kibertoad Hi there sir. Sadly it seems I have run out of time for Hacktoberfest to work on this issue. Would you be willing to make an "issue branch" for this PR and merge it into there? 

That way the work we did will stick around and can be used later :)

Thanks,
Andre

**Comment by kibertoad** [comment]
@AndreWillomitzer You've actually implemented 90% of the task at hand, I'm doing some final fixes to it right now, I think we can still merge it before midnight :)

**Comment by AndreWillomitzer** [comment]
@kibertoad Oh wow really?! I'm over the moon that what I got going was useful haha! That's really exciting.

Thanks for being cool about everything, our comment thread ended up 47 long lol. You and my prof were a great help.

Going to keep my peepers open to see what you implement for sure out of curiosity.

**Comment by kibertoad** [comment]
@AndreWillomitzer I think we are almost there, but final task is not firing for me for some reason :-/. I need to go now, but will be back in two hours or so. If you'll have time to take a look at what could still be wrong, that would be helpful, but if you are busy, no worries, I think I should be able to fix it today either way.

**Comment by kibertoad** [comment]
I think I managed to fix it in the last moment :D.
Can you please write documentation for new LongIntervalJob in readme.md?

**Comment by AndreWillomitzer** [comment]
@kibertoad Ahhhh I see what you did with the start/stop inside the constructor. I guess I forgot those key things about the jobs. As for documentation what did you have in mind? Most of what gets handled probably has nothing to do with the user doing anything it's all behind the scenes isn't it?

I too have to disappear for a bit but will be back tonight if you still need the README done :D But if you want to merge the PR and do it too that's fine with me!

Thanks!

**Comment by AndreWillomitzer** [comment]
@kibertoad Thanks again for letting me work on this it was a super super cool experience and a unique issue to solve haha, probably something I'll remember forever honestly. It was a lot of brain-cramping to get to the solution but so worth it.

If you need any help in the future I am sure we will have to commit something to a repo in the future so I'll keep my eyes open :D

All the best,

Andre!

**Comment by kibertoad** [comment]
@AndreWillomitzer It was a pleasure! You definitely are going to have bright future in software engineering. And I hope that we get to collaborate again, on this project or some other!

**Pull request merged**
