### PR TITLE
Improve async error handling

### LINKED ISSUE #54: Insert In DB On Error of AsyncTask
I am using AsyncTask to make an API call on schedule.
Regular API calls are working fine, and inserting an entry into the DB as "success" using Knex.

But, when user inputs an invalid URL, node-fetch throws an error, which is caught by the AsyncTask error handler.
At this point, I would like to log this error in the DB as well. But the knex.insert function being asyncronous, its failing to execute on the syncronous error handler function. This is what I have understood the issue is.

```
(err) => {
                console.log("HERE");

                knex('syncs_logs')
                    .insert({
                        id: item.id,
                        status_code: err,
                        error_datetime: dayjs.utc().format("YYYY-MM-DD HH:mm:ss"),
                        err_msg: JSON.stringify(err)
                    });
            }
```

Can you please help?

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #54

### CODE REVIEW

**Comment by kibertoad** [comment]
@iamsid Could you please review?

**Comment by iamsid** [comment]
@kibertoad Thanks a lot for working on this. Unfortunately, I am a beginner when it comes to Git & NPM. So not sure how to install this PR via npm and test.

From my limited JS experience, I can see from the code that changes you have implemented should take care of the issue I am facing with async calls in error handling. And additional error handling on faliure of error handler looks good too.

**Comment by kibertoad** [comment]
No worries, thank you for reviewing the code! Will release a version with these improvements shortly.

**Comment by iamsid** [comment]
@kibertoad Will the latest version be available via npm? I still see version 1.5.0 there.
I tried re-installing it, but still getting the older files.

**Comment by kibertoad** [comment]
@iamsid Sorry for delay, wanted to also address browser incompatibility I introduced in that PR, which is now done. Just published 1.6.0. Please let me now if it works for you!

**Pull request merged**
